export function generateBillHtml(bill: {
  vendorName: string;
  customerName: string;
  items: {
    productName: string;
    quantity: number;
    unit: string;
    unitPrice: number;
    totalPrice: number;
  }[];
  totalAmount: number;
  memo?: string;
  createdAt?: string;
}) {
  const date = bill.createdAt
    ? new Date(bill.createdAt).toLocaleDateString("ko-KR", {
        year: "numeric",
        month: "long",
        day: "numeric",
        hour: "2-digit",
        minute: "2-digit",
      })
    : new Date().toLocaleDateString("ko-KR", {
        year: "numeric",
        month: "long",
        day: "numeric",
        hour: "2-digit",
        minute: "2-digit",
      });

  const itemsHtml = bill.items
    .map(
      (item, i) => `
      <tr>
        <td style="padding:8px 12px;border-bottom:1px solid #eee;">${i + 1}</td>
        <td style="padding:8px 12px;border-bottom:1px solid #eee;">${item.productName}</td>
        <td style="padding:8px 12px;border-bottom:1px solid #eee;text-align:center;">${item.quantity} ${item.unit}</td>
        <td style="padding:8px 12px;border-bottom:1px solid #eee;text-align:right;">₩${item.unitPrice.toLocaleString()}</td>
        <td style="padding:8px 12px;border-bottom:1px solid #eee;text-align:right;font-weight:600;">₩${item.totalPrice.toLocaleString()}</td>
      </tr>
    `
    )
    .join("");

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <style>
        body { font-family: -apple-system, 'Malgun Gothic', sans-serif; margin:0; padding:20px; color:#333; }
        .header { text-align:center; border-bottom:3px solid #2D4D23; padding-bottom:16px; margin-bottom:20px; }
        .header h1 { color:#2D4D23; font-size:28px; margin:0 0 4px; }
        .header p { color:#888; font-size:13px; margin:0; }
        .info { display:flex; justify-content:space-between; margin-bottom:20px; }
        .info-box { background:#f9f9f9; padding:12px 16px; border-radius:8px; flex:1; margin:0 4px; }
        .info-label { font-size:11px; color:#888; text-transform:uppercase; letter-spacing:1px; }
        .info-value { font-size:16px; font-weight:700; margin-top:4px; }
        table { width:100%; border-collapse:collapse; margin:16px 0; }
        th { background:#2D4D23; color:white; padding:10px 12px; text-align:left; font-size:13px; }
        th:nth-child(3), th:nth-child(4), th:nth-child(5) { text-align:right; }
        td { font-size:14px; }
        .total-row { background:#f0f7f0; }
        .total-row td { padding:12px; font-size:18px; font-weight:700; color:#2D4D23; }
        .footer { text-align:center; margin-top:30px; padding-top:16px; border-top:1px solid #eee; color:#aaa; font-size:11px; }
        .memo { background:#fffbeb; padding:10px 14px; border-radius:8px; margin:12px 0; font-size:13px; color:#92400e; }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>ShijangMe</h1>
        <p>Wholesale Market Invoice</p>
      </div>

      <div style="display:flex;gap:8px;margin-bottom:20px;">
        <div class="info-box">
          <div class="info-label">Vendor</div>
          <div class="info-value">${bill.vendorName}</div>
        </div>
        <div class="info-box">
          <div class="info-label">Customer</div>
          <div class="info-value">${bill.customerName}</div>
        </div>
        <div class="info-box">
          <div class="info-label">Date</div>
          <div class="info-value" style="font-size:13px;">${date}</div>
        </div>
      </div>

      <table>
        <thead>
          <tr>
            <th>#</th>
            <th>Product</th>
            <th style="text-align:center;">Qty</th>
            <th style="text-align:right;">Unit Price</th>
            <th style="text-align:right;">Total</th>
          </tr>
        </thead>
        <tbody>
          ${itemsHtml}
          <tr class="total-row">
            <td colspan="4" style="text-align:right;padding:12px;">TOTAL</td>
            <td style="text-align:right;padding:12px;">₩${bill.totalAmount.toLocaleString()}</td>
          </tr>
        </tbody>
      </table>

      ${bill.memo ? `<div class="memo">📝 ${bill.memo}</div>` : ""}

      <div class="footer">
        Thank you for your business!<br/>
        Generated by ShijangMe
      </div>
    </body>
    </html>
  `;
}
