export function generateLoanHtml(loan: {
  lenderName: string;
  borrowerName: string;
  loanDate: string;
  status: string;
  items: {
    productName: string;
    quantity: number;
    unit: string;
    unitPrice: number;
    totalPrice: number;
  }[];
  totalAmount: number;
  paidAt?: string;
}) {
  const date = new Date(loan.loanDate).toLocaleDateString("ko-KR", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const statusBadge =
    loan.status === "PAID"
      ? '<span style="background:#DEF7EC;color:#03543F;padding:4px 12px;border-radius:20px;font-weight:700;">PAID</span>'
      : loan.status === "OVERDUE"
        ? '<span style="background:#FDE8E8;color:#9B1C1C;padding:4px 12px;border-radius:20px;font-weight:700;">OVERDUE</span>'
        : '<span style="background:#FEF3C7;color:#92400E;padding:4px 12px;border-radius:20px;font-weight:700;">UNPAID</span>';

  const itemsHtml = loan.items
    .map(
      (item, i) => `
      <tr>
        <td style="padding:8px 12px;border-bottom:1px solid #eee;">${i + 1}</td>
        <td style="padding:8px 12px;border-bottom:1px solid #eee;">${item.productName}</td>
        <td style="padding:8px 12px;border-bottom:1px solid #eee;text-align:center;">${item.quantity} ${item.unit}</td>
        <td style="padding:8px 12px;border-bottom:1px solid #eee;text-align:right;">₩${item.unitPrice.toLocaleString()}</td>
        <td style="padding:8px 12px;border-bottom:1px solid #eee;text-align:right;font-weight:600;">₩${item.totalPrice.toLocaleString()}</td>
      </tr>`
    )
    .join("");

  return `<!DOCTYPE html>
<html><head><meta charset="utf-8">
<style>
  body{font-family:-apple-system,'Malgun Gothic',sans-serif;margin:0;padding:20px;color:#333}
  .header{text-align:center;border-bottom:3px solid #1a1a2e;padding-bottom:16px;margin-bottom:20px}
  .header h1{color:#1a1a2e;font-size:28px;margin:0 0 4px}
  .header p{color:#888;font-size:13px;margin:0}
  .info-box{background:#f9f9f9;padding:12px 16px;border-radius:8px;flex:1;margin:0 4px}
  .info-label{font-size:11px;color:#888;text-transform:uppercase;letter-spacing:1px}
  .info-value{font-size:16px;font-weight:700;margin-top:4px}
  table{width:100%;border-collapse:collapse;margin:16px 0}
  th{background:#1a1a2e;color:white;padding:10px 12px;text-align:left;font-size:13px}
  th:nth-child(3),th:nth-child(4),th:nth-child(5){text-align:right}
  td{font-size:14px}
  .total-row{background:#f0f0f7}
  .total-row td{padding:12px;font-size:18px;font-weight:700;color:#1a1a2e}
  .footer{text-align:center;margin-top:30px;padding-top:16px;border-top:1px solid #eee;color:#aaa;font-size:11px}
  .status{text-align:center;margin:12px 0}
</style></head><body>
  <div class="header">
    <h1>ShijangMe</h1>
    <p>Inter-Vendor Loan Agreement</p>
  </div>
  <div class="status">${statusBadge}</div>
  <div style="display:flex;gap:8px;margin-bottom:20px">
    <div class="info-box">
      <div class="info-label">Lender (gave products)</div>
      <div class="info-value">${loan.lenderName}</div>
    </div>
    <div class="info-box">
      <div class="info-label">Borrower (received)</div>
      <div class="info-value">${loan.borrowerName}</div>
    </div>
    <div class="info-box">
      <div class="info-label">Loan Date</div>
      <div class="info-value" style="font-size:13px">${date}</div>
    </div>
  </div>
  <table><thead><tr>
    <th>#</th><th>Product</th><th style="text-align:center">Qty</th>
    <th style="text-align:right">Unit Price</th><th style="text-align:right">Total</th>
  </tr></thead><tbody>
    ${itemsHtml}
    <tr class="total-row">
      <td colspan="4" style="text-align:right;padding:12px">TOTAL</td>
      <td style="text-align:right;padding:12px">₩${loan.totalAmount.toLocaleString()}</td>
    </tr>
  </tbody></table>
  ${loan.paidAt ? `<p style="text-align:center;color:#03543F;font-weight:700">Paid on: ${new Date(loan.paidAt).toLocaleDateString("ko-KR")}</p>` : ""}
  <div class="footer">This is a loan agreement between vendors.<br/>Generated by ShijangMe</div>
</body></html>`;
}
