export enum NoticeCategory {
  FAQ = "FAQ",
  TERMS = "TERMS",
  INQUIRY = "INQUIRY",
}
export enum NoticeStatus {
  HOLD = "HOLD",
  ACTIVE = "ACTIVE",
  DELETE = "DELETE",
}

export enum NoticeFor {
  PRODUCT = "PRODUCT",
  PAYMENT = "PAYMENT",
  FOR_BUYERS = "FOR_BUYERS",
  COMMUNITY = "COMMUNITY",
  OTHER = "OTHER",
  ALL = "ALL",
}

export enum NotificationType {
  PRODUCT_SOLD = "PRODUCT_SOLD",
  PRODUCT_LIKED = "PRODUCT_LIKED",
  NEW_FOLLOWER = "NEW_FOLLOWER",
  PRODUCT_DELETED = "PRODUCT_DELETED",
  SUBSCRIBED = "SUBSCRIBED",
  UNSUBSCRIBED = "UNSUBSCRIBED",
  SEND_MESSAGE = "SEND_MESSAGE",
}
